version: 2
root-markers:
  - .git/
tools:
  prettier: &prettier
    format-command: 'eslint --stdin-filename ${INPUT} && prettier --stdin-filepath ${INPUT}'
    format-stdin: true
    lint-command: 'eslint -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"
languages:
  typescript:
    - <<: *prettier
  typescriptreact:
    - <<: *prettier
