version: '2'
services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    container_name: soc_information_api_db
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: containers/app/Dockerfile
    container_name: soc_information_api_rails
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
      - tmp-data:/app/tmp
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      ENVIRONMENT: development
      TZ: Asia/Tokyo
    mem_limit: 250m
  nginx:
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
    container_name: soc_information_api_nginx
    volumes:
      - tmp-data:/app/tmp
    ports:
      - "80:80"
    depends_on:
      - app
    mem_limit: 250m
volumes:
  mysql-data:
    driver: local
  tmp-data:
