[[plugins]] # TOMLのシンタックスハイライト
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'rhysd/nyaovim-popup-tooltip'

[[plugins]]
repo = 'rhysd/nyaovim-mini-browser'

# Rust
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
hook_source = '''
let g:rustfmt_autosave = 1
let g:rustfmt_command = '$HOME/.cargo/bin/rustfmt'
'''

[[plugins]]
repo = 'IN3D/vim-raml'

[[plugins]]
repo = "let-def/vimbufsync"
on_ft = "coq"

[[plugins]]
repo = "the-lambda-church/coquille"
on_ft = "coq"
depends = ["vimbufsync"]
hook_source = """
"""

[[plugins]]
repo='zah/nim.vim'
on_ft="nim"

# MarkDown
[[plugins]]
repo='plasticboy/vim-markdown'
on_ft = ['markdown', 'mkd']
hook_add='''
    let g:vim_markdown_folding_disabled = 1
    let g:vim_markdown_auto_insert_bullets = 0
    let g:vim_markdown_new_list_item_indent = 0
'''

[[plugins]]
on_ft = ['markdown', 'mkd']
hook_source = '''
let g:rustfmt_autosave = 1
let g:rustfmt_command = '$HOME/.cargo/bin/rustfmt'
'''

[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
on_ft = 'rust'
depends = ['deoplete.nvim']
hook_source = '''
    let g:deoplete#sources#rust#racer_binary="$HOME/.cargo/bin/racer"
    let g:deoplete#sources#rust#rust_source_path='$HOME/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/'
    let g:deoplete#sources#rust#show_duplicates=1
    let g:deoplete#sources#rust#disable_keymap=1
    nmap <buffer> gd <plug>DeopleteRustGoToDefinitionDefault
    nmap <buffer> K  <plug>DeopleteRustShowDocumentation
'''

[[plugins]]
repo = 'IN3D/vim-raml'

[[plugins]]
repo = "let-def/vimbufsync"
on_ft = "coq"

[[plugins]]
repo = "the-lambda-church/coquille"
on_ft = "coq"
depends = ["vimbufsync"]
hook_source = """
"""

[[plugins]]
repo='zah/nim.vim'
on_ft="nim"


# MarkDown
[[plugins]]
repo='plasticboy/vim-markdown'
on_ft='markdown'
hook_add='''
    let g:vim_markdown_folding_disabled = 1
    let g:vim_markdown_auto_insert_bullets = 0
    let g:vim_markdown_new_list_item_indent = 0
'''

[[plugins]]
on_ft='markdown'
repo = 'godlygeek/tabular'

[[plugins]]
repo='mattn/vim-goimports'
