[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # color scheme
repo = 'w0ng/vim-hybrid'
hook_add = '''
set background=dark
colorscheme hybrid
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
let NERDTreeShowHidden = 1
nnoremap <silent><C-e> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ], [ 'readonly', 'absolutepath', 'modified' ] ],
      \ }
      \ }
'''

# Indent
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_source = '''
    let g:indent_guides_guide_size = 1
    let g:indent_guides_enable_on_vim_startup = 1
    let g:indent_guides_exclude_filetypes = ['help', 'nerdtree']
'''

## Git gutter
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_source = '''
    nmap <Leader>h] <Plug>GitGutterNextHunk
    nmap <Leader>h[ <Plug>GitGutterPrevHunk
    set updatetime=250
'''

## Git fugitive
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo='jalvesaq/Nvim-R'

[[plugins]]
repo='easymotion/vim-easymotion'
hook_add='''
let g:EasyMotion_do_mapping = 0
let g:EasyMotion_smartcase = 1
map s <Plug>(easymotion-overwin-f)
map s <Plug>(easymotion-overwin-f2)
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)
'''

[[plugins]]
repo='prabirshrestha/asyncomplete.vim'

[[plugins]]
repo='mattn/vim-goimports'
hook_add='''
let g:goimports = 1
let g:goimports_simplify = 1
'''
merged='0'

[[plugins]]
repo='leafgarland/typescript-vim'

[[plugins]]
repo='peitalin/vim-jsx-typescript'
